// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/gabapcia/packsmath/internal/pack"
	"sync"
)

// Ensure, that ServiceMock does implement pack.Service.
// If this is not the case, regenerate this file with moq.
var _ pack.Service = &ServiceMock{}

// ServiceMock is a mock implementation of pack.Service.
//
//	func TestSomethingThatUsesService(t *testing.T) {
//
//		// make and configure a mocked pack.Service
//		mockedService := &ServiceMock{
//			DeletePackSizeFunc: func(ctx context.Context, size int) error {
//				panic("mock out the DeletePackSize method")
//			},
//			ListPackSizesFunc: func(ctx context.Context) ([]int, error) {
//				panic("mock out the ListPackSizes method")
//			},
//			RegisterPackSizeFunc: func(ctx context.Context, size int) error {
//				panic("mock out the RegisterPackSize method")
//			},
//		}
//
//		// use mockedService in code that requires pack.Service
//		// and then make assertions.
//
//	}
type ServiceMock struct {
	// DeletePackSizeFunc mocks the DeletePackSize method.
	DeletePackSizeFunc func(ctx context.Context, size int) error

	// ListPackSizesFunc mocks the ListPackSizes method.
	ListPackSizesFunc func(ctx context.Context) ([]int, error)

	// RegisterPackSizeFunc mocks the RegisterPackSize method.
	RegisterPackSizeFunc func(ctx context.Context, size int) error

	// calls tracks calls to the methods.
	calls struct {
		// DeletePackSize holds details about calls to the DeletePackSize method.
		DeletePackSize []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Size is the size argument value.
			Size int
		}
		// ListPackSizes holds details about calls to the ListPackSizes method.
		ListPackSizes []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// RegisterPackSize holds details about calls to the RegisterPackSize method.
		RegisterPackSize []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Size is the size argument value.
			Size int
		}
	}
	lockDeletePackSize   sync.RWMutex
	lockListPackSizes    sync.RWMutex
	lockRegisterPackSize sync.RWMutex
}

// DeletePackSize calls DeletePackSizeFunc.
func (mock *ServiceMock) DeletePackSize(ctx context.Context, size int) error {
	if mock.DeletePackSizeFunc == nil {
		panic("ServiceMock.DeletePackSizeFunc: method is nil but Service.DeletePackSize was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Size int
	}{
		Ctx:  ctx,
		Size: size,
	}
	mock.lockDeletePackSize.Lock()
	mock.calls.DeletePackSize = append(mock.calls.DeletePackSize, callInfo)
	mock.lockDeletePackSize.Unlock()
	return mock.DeletePackSizeFunc(ctx, size)
}

// DeletePackSizeCalls gets all the calls that were made to DeletePackSize.
// Check the length with:
//
//	len(mockedService.DeletePackSizeCalls())
func (mock *ServiceMock) DeletePackSizeCalls() []struct {
	Ctx  context.Context
	Size int
} {
	var calls []struct {
		Ctx  context.Context
		Size int
	}
	mock.lockDeletePackSize.RLock()
	calls = mock.calls.DeletePackSize
	mock.lockDeletePackSize.RUnlock()
	return calls
}

// ListPackSizes calls ListPackSizesFunc.
func (mock *ServiceMock) ListPackSizes(ctx context.Context) ([]int, error) {
	if mock.ListPackSizesFunc == nil {
		panic("ServiceMock.ListPackSizesFunc: method is nil but Service.ListPackSizes was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockListPackSizes.Lock()
	mock.calls.ListPackSizes = append(mock.calls.ListPackSizes, callInfo)
	mock.lockListPackSizes.Unlock()
	return mock.ListPackSizesFunc(ctx)
}

// ListPackSizesCalls gets all the calls that were made to ListPackSizes.
// Check the length with:
//
//	len(mockedService.ListPackSizesCalls())
func (mock *ServiceMock) ListPackSizesCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockListPackSizes.RLock()
	calls = mock.calls.ListPackSizes
	mock.lockListPackSizes.RUnlock()
	return calls
}

// RegisterPackSize calls RegisterPackSizeFunc.
func (mock *ServiceMock) RegisterPackSize(ctx context.Context, size int) error {
	if mock.RegisterPackSizeFunc == nil {
		panic("ServiceMock.RegisterPackSizeFunc: method is nil but Service.RegisterPackSize was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Size int
	}{
		Ctx:  ctx,
		Size: size,
	}
	mock.lockRegisterPackSize.Lock()
	mock.calls.RegisterPackSize = append(mock.calls.RegisterPackSize, callInfo)
	mock.lockRegisterPackSize.Unlock()
	return mock.RegisterPackSizeFunc(ctx, size)
}

// RegisterPackSizeCalls gets all the calls that were made to RegisterPackSize.
// Check the length with:
//
//	len(mockedService.RegisterPackSizeCalls())
func (mock *ServiceMock) RegisterPackSizeCalls() []struct {
	Ctx  context.Context
	Size int
} {
	var calls []struct {
		Ctx  context.Context
		Size int
	}
	mock.lockRegisterPackSize.RLock()
	calls = mock.calls.RegisterPackSize
	mock.lockRegisterPackSize.RUnlock()
	return calls
}
